name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libxkbcommon-dev libxss1 libgtk-3-dev

      - name: Install Dependencies
        run: npm install

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Build SQLite3
        run: npm run resqlite

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build-w

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run build-m

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build-l

      - name: List build artifacts
        run: ls -la out/

      - name: List build artifacts
        run: ls -la out/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/ee-*.exe
            out/ee-*.dmg
            out/ee-*.AppImage
            out/ee-*.deb
            out/ee-*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}